# Generated by Django 5.0.4 on 2024-05-07 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Portfolio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('phone_number', models.CharField(max_length=20)),
                ('mailing_address', models.TextField(blank=True)),
                ('professional_title', models.CharField(max_length=255)),
                ('professional_summary', models.TextField()),
                ('skills', models.TextField(help_text='Enter skills separated by commas')),
                ('job_titles', models.TextField(help_text='Enter job titles separated by commas')),
                ('companies_worked_at', models.TextField(help_text='Enter companies separated by commas')),
                ('employment_dates', models.CharField(max_length=255)),
                ('job_descriptions', models.TextField()),
                ('institutions_attended', models.TextField(help_text='Enter institutions separated by commas')),
                ('degrees_certifications', models.TextField(help_text='Enter degrees or certifications separated by commas')),
                ('years_of_attendance', models.CharField(max_length=255)),
                ('project_titles', models.TextField(help_text='Enter project titles separated by commas')),
                ('project_descriptions', models.TextField()),
                ('project_links', models.TextField(help_text='Enter project URLs separated by commas')),
                ('project_images', models.ImageField(blank=True, null=True, upload_to='images/')),
                ('achievements', models.TextField(blank=True)),
                ('references_names', models.TextField()),
                ('references_contact_info', models.TextField()),
                ('linkedin_url', models.URLField(blank=True)),
                ('github_url', models.URLField(blank=True)),
                ('other_social_urls', models.TextField(blank=True)),
                ('volunteer_work', models.TextField(blank=True)),
                ('languages_spoken', models.TextField(blank=True)),
                ('hobbies_interests', models.TextField(blank=True)),
            ],
        ),
    ]
